apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment-baseline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: baseline
  template:
    metadata:
      labels:
        app: my-app
        version: baseline
    spec:
      containers:
      - name: my-app
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP