apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment-baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: baseline
  template:
    metadata:
      labels:
        app: my-app
        version: baseline
    spec:
      containers:
      - name: my-app
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: baseline-svc
spec:
  selector:
    app: my-app
    version: baseline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-ingress
  namespace: webinar
spec:
  rules:
    - host: webinar.dev.bimeister.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: baseline-svc
              port:
                number: 80