apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: canary
  template:
    metadata:
      labels:
        app: my-app
        version: canary
    spec:
      containers:
      - name: my-app
        image: nginx:1.22
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  selector:
    app: my-app
    version: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress
  namespace: webinar
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  rules:
    - host: webinar.dev.bimeister.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: canary-svc
              port:
                number: 80